import { expect, test, type Page } from '@playwright/test'

async function signIn(page: Page, route = '/research') {
  await page.goto(route)
  await page.getByLabel('Username').fill('founder')
  await page.getByLabel('Password').fill('browser-secret')
  await page.getByRole('button', { name: 'Sign in' }).click()
  await expect(page.getByRole('heading', { name: route === '/research' ? 'Research' : 'Companies' })).toBeVisible()
}

test('Research renders the approved desktop structure and company details', async ({ page }) => {
  await page.clock.install({ time: new Date('2026-09-23T12:00:00Z') })
  await signIn(page)
  await expect(page.getByText('Companies recorded')).toBeVisible()
  await expect(page.getByText('Showing 1–8 of 12 companies')).toBeVisible()
  await page.getByRole('row', { name: /Rift Dynamics/ }).click()
  const drawer = page.getByRole('complementary', { name: 'Company details' })
  await expect(drawer.getByText('Operations software for distributed teams.')).toBeVisible()
  await drawer.getByRole('tab', { name: 'Contacts' }).click()
  await expect(drawer.getByRole('link', { name: 'Alex Carter' })).toBeVisible()
  await drawer.getByRole('tab', { name: 'Overview' }).click()
  await page.screenshot({ path: '/tmp/research-render.png', fullPage: true })
  await expect(page).toHaveScreenshot('research-desktop.png', { fullPage: true })
})

test('company filters, sort, selection, and navigation stay in the URL', async ({ page }) => {
  await signIn(page)
  await page.getByLabel('Sort companies').selectOption('name')
  await expect(page).toHaveURL(/sort=name/)
  await page.getByRole('button', { name: 'Next page' }).click()
  await expect(page).toHaveURL(/page=2/)
  await expect(page.getByText('Showing 9–12 of 12 companies')).toBeVisible()
  await page.getByPlaceholder('Search companies, industries, or countries…').fill('Rift')
  await expect(page).toHaveURL(/q=Rift/)
  await expect(page.getByText('Showing 1–1 of 1 companies')).toBeVisible()
  await page.getByRole('row', { name: /Rift Dynamics/ }).click()
  await expect(page).toHaveURL(/company=domain%3Arift.test/)
  await page.getByRole('link', { name: 'Companies', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Companies' })).toBeVisible()
  await expect(page.getByText('Showing 1–8 of 12 companies')).toBeVisible()
  await expect(page.getByLabel('Username')).not.toBeVisible()
})

test('Companies resolves a real profile and refreshes authoritative data', async ({ page, request }) => {
  await signIn(page, '/companies')
  await page.getByPlaceholder('Search companies, industries, or countries…').fill('Atlas')
  await expect(page.getByText('Showing 1–1 of 1 companies')).toBeVisible()
  await page.getByRole('row', { name: /Atlas Works/ }).click()
  const drawer = page.getByRole('complementary', { name: 'Company details' })
  await expect(drawer.getByText('No company description is saved.')).toBeVisible()
  await drawer.getByRole('button', { name: 'Resolve profile' }).click()
  await drawer.getByLabel('Founder action token').fill('wrong')
  await drawer.getByRole('button', { name: 'Resolve profile' }).click()
  await expect(drawer.getByRole('alert')).toContainText('founder action token')
  await drawer.getByLabel('Founder action token').fill('browser-action')
  await drawer.getByRole('button', { name: 'Resolve profile' }).click()
  await expect(drawer.getByRole('status')).toContainText('Company profile updated')
  await expect(drawer.getByText('Profile resolved during browser validation.')).toBeVisible()
  const response = await request.get('/company/sales/companies/domain%3Aatlas.test', { headers: { Authorization: `Basic ${btoa('founder:browser-secret')}` } })
  expect(response.ok()).toBeTruthy()
  const record = await response.json()
  expect(record.has_profile).toBe(true)
  expect(record.description).toBe('Profile resolved during browser validation.')
})

test('research dialog and mobile company cards are usable', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await signIn(page)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.getByRole('button', { name: 'New research' }).click()
  await expect(page.getByRole('dialog', { name: 'New company research' })).toBeVisible()
  await page.getByRole('dialog').getByRole('button', { name: 'Cancel' }).click()
  await page.getByRole('row', { name: /Rift Dynamics/ }).click()
  await expect(page.getByRole('complementary', { name: 'Company details' })).toBeVisible()
  await page.getByRole('button', { name: 'Close company details' }).click()
  await expect(page.getByRole('complementary', { name: 'Company details' })).not.toBeVisible()
})
