import { expect, test } from '@playwright/test'

async function signIn(page: import('@playwright/test').Page) {
  await page.goto('/contacts')
  await page.getByLabel('Username').fill('founder')
  await page.getByLabel('Password').fill('browser-secret')
  await page.getByRole('button', { name: 'Sign in' }).click()
  await expect(page.getByRole('heading', { name: 'Contacts' })).toBeVisible()
}

test('invalid dashboard credentials show an inline error and allow retry', async ({ page }) => {
  await page.goto('/contacts')
  await expect(page.getByLabel('Username')).toHaveValue('')
  await page.getByLabel('Username').fill('founder')
  await page.getByLabel('Password').fill('wrong')
  await page.getByRole('button', { name: 'Sign in' }).click()
  await expect(page.getByRole('alert')).toContainText('Incorrect dashboard username or password')
  await page.getByLabel('Password').fill('browser-secret')
  await page.getByRole('button', { name: 'Sign in' }).click()
  await expect(page.getByRole('heading', { name: 'Contacts' })).toBeVisible()
})

test('approved desktop visual layout', async ({ page }) => {
  await page.clock.install({ time: new Date('2026-09-23T12:00:00Z') })
  await signIn(page)
  await page.getByRole('row', { name: /Alex Carter/ }).click()
  await expect(page.getByText('alex@rift.test')).toBeVisible()
  await page.screenshot({ path: '/tmp/contacts-render.png', fullPage: true })
  await expect(page).toHaveScreenshot('contacts-desktop.png', { fullPage: true })
})

test('contact selection, gated draft and authoritative refresh', async ({ page, request }) => {
  await signIn(page)
  await expect(page.getByText('Total contacts')).toBeVisible()
  await expect(page.getByText('Showing 1–10 of 12 contacts')).toBeVisible()
  await page.getByRole('row', { name: /Alex Carter/ }).click()
  await expect(page.getByRole('complementary', { name: 'Contact details' })).toBeVisible()
  await expect(page.getByText('alex@rift.test')).toBeVisible()
  await page.getByRole('tab', { name: 'Company' }).click()
  await expect(page.getByText('Operations software for distributed teams.')).toBeVisible()
  await page.getByRole('tab', { name: 'Overview' }).click()
  const drawer = page.getByRole('complementary', { name: 'Contact details' })
  await drawer.getByRole('button', { name: 'Draft outreach', exact: true }).click()
  await page.getByLabel('Founder action token').fill('wrong')
  await drawer.getByRole('button', { name: 'Save draft' }).click()
  await expect(page.getByRole('alert')).toContainText('founder action token')
  await page.getByLabel('Founder action token').fill('browser-action')
  await drawer.getByRole('button', { name: 'Save draft' }).click()
  await expect(page.getByRole('status')).toContainText('Draft saved')
  await expect(page.getByText('Introduction to Rift Dynamics')).toBeVisible()
  const selectedId = new URL(page.url()).searchParams.get('contact')
  const response = await request.get(`/company/sales/contacts/${selectedId}`, { headers: { Authorization: `Basic ${btoa('founder:browser-secret')}` } })
  expect(response.ok()).toBeTruthy()
  expect((await response.json()).stage).toBe('draft_ready')
})

test('filters, sorting and page remain in URL', async ({ page }) => {
  await signIn(page)
  await page.getByLabel('Sort contacts').selectOption('name')
  await expect(page).toHaveURL(/sort=name/)
  await page.getByRole('button', { name: 'Next page' }).click()
  await expect(page).toHaveURL(/page=2/)
  await expect(page.getByText('Showing 11–12 of 12 contacts')).toBeVisible()
  await page.getByPlaceholder('Search contacts, companies, or roles…').fill('Rift')
  await expect(page).toHaveURL(/q=Rift/)
  await expect(page.getByText('Showing 1–1 of 1 contacts')).toBeVisible()
  await page.reload()
  await page.getByLabel('Username').fill('founder')
  await page.getByLabel('Password').fill('browser-secret')
  await page.getByRole('button', { name: 'Sign in' }).click()
  await expect(page.getByText('Showing 1–1 of 1 contacts')).toBeVisible()
  await page.getByPlaceholder('Search contacts, companies, or roles…').fill('no such company')
  await expect(page.getByRole('heading', { name: 'No contacts found' })).toBeVisible()
})

test('mobile cards and missing contact data remain usable', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await signIn(page)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.getByRole('row', { name: /Sophie Lee/ }).click()
  const drawer = page.getByRole('complementary', { name: 'Contact details' })
  await expect(drawer.getByText('No email on record')).toBeVisible()
  await expect(drawer.getByText('An email is needed to draft outreach.')).toBeVisible()
  await drawer.getByRole('button', { name: 'Close contact details' }).click()
  await expect(drawer).not.toBeVisible()
})
