import { expect, test } from '@playwright/test'

const auth = `Basic ${btoa('founder:browser-secret')}`

test('first user resumes and activates a program using saved sales records', async ({ page, request }) => {
  await page.goto('/onboarding')
  await page.getByLabel('Username').fill('founder')
  await page.getByLabel('Password').fill('browser-secret')
  await page.getByRole('button', { name: 'Sign in' }).click()
  await expect(page.getByRole('heading', { name: 'First-run setup' })).toBeVisible()
  await expect(page.getByRole('heading', { name: '1. Your company', exact: true })).toBeVisible()
  await page.screenshot({ path: '/tmp/autoevolve-onboarding-first-run.png', fullPage: true })
  await expect(page).toHaveScreenshot('onboarding-first-run.png', { fullPage: true })
  await page.getByLabel('Founder action token').fill('browser-action')

  await page.getByLabel('Company name').fill('Example Studio')
  await page.getByLabel('Website').fill('https://wrong.test')
  await page.getByLabel('Objective').fill('Find qualified operations buyers')
  await page.getByLabel('Primary market').fill('United States')
  await page.getByRole('button', { name: 'Save and continue' }).click()
  await expect(page.getByRole('heading', { name: /Research and confirm/ })).toBeVisible()
  await page.reload()
  await page.getByLabel('Username').fill('founder')
  await page.getByLabel('Password').fill('browser-secret')
  await page.getByRole('button', { name: 'Sign in' }).click()
  await expect(page.getByRole('heading', { name: /Research and confirm/ })).toBeVisible()
  await page.getByLabel('Founder action token').fill('browser-action')
  await page.getByRole('button', { name: 'Change company or website' }).click()
  await page.getByLabel('Website').fill('https://studio.test')
  await page.getByRole('button', { name: 'Save and continue' }).click()
  await expect(page.getByRole('heading', { name: /Research and confirm/ })).toBeVisible()
  await page.getByRole('button', { name: 'Research website' }).click()
  await expect(page.getByText('Source: website + companyenrich')).toBeVisible()
  await expect(page.getByText('Website evidence:')).toBeVisible()
  await page.getByRole('button', { name: 'Confirm company context' }).click()

  await expect(page.getByRole('heading', { name: /Define your first program/ })).toBeVisible()
  await expect(page.getByLabel('Offers · one per line')).toHaveValue('Workflow audit')
  await expect(page.getByLabel('ICP industry')).toHaveValue('Software')
  await expect(page.getByLabel('Company sizes · one per line')).toHaveValue('50-500 employees')
  await expect(page.getByLabel('Ideal customer profile')).toHaveValue('Midmarket operations teams with manual handoffs')
  await expect(page.getByLabel('Buyer titles · one per line')).toHaveValue('Operations Director')
  await expect(page.getByLabel('Markets · one per line')).toHaveValue('United States')
  await expect(page.getByLabel('Positive signals · one per line')).toHaveValue('Growing operations team')
  await expect(page.getByLabel('Exclusions · one per line')).toHaveValue('Outside the primary market')
  await expect(page.getByLabel('Tone')).toHaveValue('Direct and factual')
  await expect(page.getByLabel('Approved claims · one per line')).toHaveValue('Operations workflow support')
  await expect(page.getByLabel('Forbidden claims · one per line')).toHaveValue('Guaranteed revenue')
  await page.getByLabel('Tone').fill('Warm and precise')
  await page.reload()
  await page.getByLabel('Username').fill('founder')
  await page.getByLabel('Password').fill('browser-secret')
  await page.getByRole('button', { name: 'Sign in' }).click()
  await expect(page.getByLabel('Tone')).toHaveValue('Warm and precise')
  await page.getByLabel('Founder action token').fill('browser-action')
  await page.getByRole('button', { name: 'Save strategy' }).click()
  await expect(page.getByRole('heading', { name: /Find your first companies/ })).toBeVisible()
  await page.getByRole('button', { name: 'Run company search' }).click()
  await expect(page.getByText('Acme Systems')).toBeVisible()
  await expect(page.getByText('Other Systems')).toBeVisible()
  await page.getByLabel('Rating for Acme Systems').selectOption('good')
  await page.getByText('Acme Systems').locator('..').locator('..').getByRole('button', { name: 'Save rating' }).click()
  await page.getByLabel('Rating for Other Systems').selectOption('bad')
  await page.getByLabel('Reason for Other Systems').selectOption('wrong_geography')
  await page.getByText('Other Systems').locator('..').locator('..').getByRole('button', { name: 'Save rating' }).click()
  await expect(page.getByText('country:Canada')).toBeVisible()
  await page.getByRole('button', { name: 'Approve proposal' }).click()
  await expect(page.getByRole('heading', { name: /Resolve one buyer/ })).toBeVisible()
  await page.getByRole('button', { name: 'Resolve one buyer' }).click()
  await expect(page.getByRole('heading', { name: /Create first outreach drafts/ })).toBeVisible()
  await page.getByRole('button', { name: 'Generate draft' }).click()
  await expect(page.getByRole('heading', { name: /Activate the program/ })).toBeVisible()
  await page.getByRole('button', { name: 'Activate and open Home' }).click()
  await expect(page).toHaveURL(/\/home$/)
  await expect(page.getByRole('heading', { name: 'Home' })).toBeVisible()

  const state = await request.get('/company/ui/onboarding', { headers: { Authorization: auth } })
  expect(state.status()).toBe(200)
  const body = await state.json()
  expect(body.program.status).toBe('activated')
  expect(body.program.strategy.exclusions).toContain('country:Canada')
  const candidateId = body.sample.find((item: { name: string }) => item.name === 'Acme Systems').lead_id
  const draftId = body.program.draft_ids[candidateId]
  const draft = await request.get(`/company/ui/outreach/${draftId}`, { headers: { Authorization: auth } })
  expect(draft.status()).toBe(200)
  expect((await draft.json()).status).toBe('draft')

  await page.reload()
  await page.getByLabel('Username').fill('founder')
  await page.getByLabel('Password').fill('browser-secret')
  await page.getByRole('button', { name: 'Sign in' }).click()
  await expect(page.getByRole('heading', { name: 'Home' })).toBeVisible()
  await page.getByRole('link', { name: 'Get started' }).click()
  await expect(page.getByRole('heading', { name: 'Program active' })).toBeVisible()
})

test('service-first search finds the requested contacts and supports retargeting', async ({ page }) => {
  await page.goto('/services')
  await page.getByLabel('Username').fill('founder')
  await page.getByLabel('Password').fill('browser-secret')
  await page.getByRole('button', { name: 'Sign in' }).click()
  await expect(page.getByRole('heading', { name: 'Start with a service' })).toBeVisible()
  await page.getByLabel('Service to sell').fill('Appointment scheduling for dental clinics')
  await page.getByLabel('Number of contacts').first().fill('2')
  await page.getByLabel('Founder action token').fill('browser-action')
  await page.getByRole('button', { name: 'Find contacts' }).click()
  await expect(page.getByRole('heading', { name: '2. Review saved contacts' })).toBeVisible()
  await expect(page.getByText('Alex Lee')).toBeVisible()
  await expect(page.getByText('Sam Rivera')).toBeVisible()
  await expect(page.getByText('Search keywords: dental practice, appointment scheduling')).toBeVisible()
  await expect(page.getByText('Likely buyers: Practice Manager')).toBeVisible()
  await expect(page.getByRole('link', { name: 'Review contact' }).first()).toHaveAttribute('href', /\/contacts\?contact=lead_/)
  await page.reload()
  await page.getByLabel('Username').fill('founder')
  await page.getByLabel('Password').fill('browser-secret')
  await page.getByRole('button', { name: 'Sign in' }).click()
  await expect(page.getByText('Alex Lee')).toBeVisible()
  await page.getByLabel('Founder action token').fill('browser-action')
  await page.getByLabel('Buyer industry').fill('Veterinary clinics')
  await page.getByRole('button', { name: 'Search again with edits' }).click()
  await expect(page.getByText('No contacts were saved.')).toBeVisible()
})
