import { expect, test, type Page } from '@playwright/test'

const authorization = `Basic ${btoa('founder:browser-secret')}`

async function signIn(page: Page, path: string, heading: string) {
  await page.goto(path)
  await page.getByLabel('Username').fill('founder')
  await page.getByLabel('Password').fill('browser-secret')
  await page.getByRole('button', { name: 'Sign in' }).click()
  await expect(page.getByRole('heading', { name: heading, exact: true })).toBeVisible()
}

test('desktop operational pages keep the approved visual structure', async ({ page }) => {
  await signIn(page, '/integrations', 'Integrations')
  await expect(page.getByRole('table')).toBeVisible()
  await page.getByRole('row', { name: /Outbound email/ }).getByRole('button', { name: 'Configure' }).click()
  await expect(page.getByRole('complementary', { name: 'Integration details' })).toBeVisible()
  await expect(page.getByRole('complementary', { name: 'Integration details' }).getByRole('button', { name: 'Test value' })).toBeInViewport({ ratio: 1 })
  await expect(page.getByRole('complementary', { name: 'Integration details' }).getByRole('button', { name: 'Save key' })).toBeInViewport({ ratio: 1 })
  const saveButton = await page.getByRole('complementary', { name: 'Integration details' }).getByRole('button', { name: 'Save key' }).boundingBox()
  expect(saveButton && saveButton.y + saveButton.height).toBeLessThanOrEqual(864)
  await page.mouse.move(0, 0)
  await expect(page).toHaveScreenshot('integrations-desktop.png', { fullPage: true })
  await page.getByRole('link', { name: 'Settings' }).click()
  await expect(page.getByRole('heading', { name: 'Settings', exact: true })).toBeVisible()
  await expect(page).toHaveScreenshot('settings-desktop.png', { fullPage: true })
})

test('integrations renders real key presence and saves through backend gates', async ({ page, request }) => {
  await signIn(page, '/integrations', 'Integrations')
  await expect(page.locator('.operational-metrics').getByText('Provider groups')).toBeVisible()
  await expect(page.getByRole('row', { name: /Stock media/ })).toContainText('1 / 5')
  await page.getByRole('row', { name: /Stock media/ }).getByRole('button', { name: 'Configure' }).click()
  await expect(page).toHaveURL(/integration=media/)
  const drawer = page.getByRole('complementary', { name: 'Integration details' })
  await drawer.getByLabel('Key to configure').selectOption('PIXABAY_API_KEY')
  await drawer.getByLabel('New key value').fill('browser-test-key-123')
  await drawer.getByLabel('Founder action token').fill('wrong')
  await drawer.getByRole('button', { name: 'Test value' }).click()
  await expect(drawer.getByRole('alert')).toContainText('not authorized')
  await drawer.getByLabel('Founder action token').fill('browser-action')
  await drawer.getByLabel('New key value').fill('short')
  await drawer.getByRole('button', { name: 'Test value' }).click()
  await expect(drawer.getByRole('alert')).toContainText('PIXABAY_API_KEY: looks too short for a key')
  await drawer.getByLabel('New key value').fill('browser-test-key-123')
  await drawer.getByRole('button', { name: 'Test value' }).click()
  await expect(drawer.getByRole('status')).toContainText('Backend validation passed')
  await drawer.getByRole('button', { name: 'Save key' }).click()
  await expect(drawer.getByRole('status')).toContainText('Key saved')
  await expect(page.getByRole('row', { name: /Stock media/ })).toContainText('2 / 5')
  const response = await request.get('/company/ui/integrations', { headers: { Authorization: authorization } })
  expect(response.ok()).toBeTruthy()
  expect((await response.json()).groups.find((group: { id: string }) => group.id === 'media').configured_keys).toContain('PIXABAY_API_KEY')
})

test('settings creates an organization and refreshes capability state', async ({ page, request }) => {
  await signIn(page, '/settings', 'Settings')
  await expect(page.getByLabel('Organization', { exact: true })).toHaveValue('1')
  await page.getByPlaceholder('Organization name').fill('Action Studio')
  await page.getByPlaceholder('example.org').fill('action.test')
  await page.getByRole('button', { name: 'Create organization' }).click()
  await expect(page.getByRole('status')).toContainText('Organization Action Studio created')
  await page.getByLabel('Organization', { exact: true }).selectOption({ label: 'Action Studio' })
  const capability = page.locator('.capability-item').first()
  const name = await capability.locator('strong').textContent()
  await capability.getByRole('checkbox').check()
  await page.getByRole('button', { name: 'Save capabilities' }).click()
  await expect(page.getByRole('status').last()).toContainText('Capabilities saved')
  const response = await request.get('/company/ui/settings', { headers: { Authorization: authorization } })
  expect(response.ok()).toBeTruthy()
  const body = await response.json()
  expect(body.orgs.find((org: { name: string }) => org.name === 'Action Studio').capabilities[name?.replaceAll(' ', '_') || '']).toBe(true)
  await page.getByRole('button', { name: 'Public links' }).click()
  await expect(page).toHaveURL(/section=links/)
  await expect(page.getByText('Configured destinations only')).toBeVisible()
})

test('read failure remains a failure, and 401 returns to sign-in', async ({ page }) => {
  await signIn(page, '/integrations', 'Integrations')
  await page.route('**/company/ui/integrations', route => route.fulfill({ status: 500, body: JSON.stringify({ detail: 'fixture failure' }), contentType: 'application/json' }))
  await page.reload()
  await page.getByLabel('Username').fill('founder')
  await page.getByLabel('Password').fill('browser-secret')
  await page.getByRole('button', { name: 'Sign in' }).click()
  await expect(page.getByText('Integrations could not be loaded')).toBeVisible()
  await expect(page.getByText('No integrations found')).not.toBeVisible()
  await page.unroute('**/company/ui/integrations')
  await page.getByRole('button', { name: 'Try again' }).click()
  await expect(page.getByRole('row', { name: /Stock media/ })).toBeVisible()
  await page.route('**/company/ui/integrations', route => route.fulfill({ status: 429, headers: { 'Retry-After': '3' }, body: JSON.stringify({ detail: 'rate limited' }), contentType: 'application/json' }))
  await page.reload()
  await page.getByLabel('Username').fill('founder')
  await page.getByLabel('Password').fill('browser-secret')
  await page.getByRole('button', { name: 'Sign in' }).click()
  await expect(page.getByText('Integrations could not be loaded')).toBeVisible()
  await expect(page.getByText('Try again in 3 seconds.')).toBeVisible()
  await page.unroute('**/company/ui/integrations')
  await page.route('**/company/ui/integrations', route => route.fulfill({ status: 401, body: JSON.stringify({ detail: 'Unauthorized' }), contentType: 'application/json' }))
  await page.reload()
  await page.getByLabel('Username').fill('founder')
  await page.getByLabel('Password').fill('browser-secret')
  await page.getByRole('button', { name: 'Sign in' }).click()
  await expect(page.getByLabel('Username')).toBeVisible()
  await expect(page.getByRole('alert')).toContainText('credentials were rejected')
})

test('operational pages remain usable on a narrow viewport', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await signIn(page, '/integrations', 'Integrations')
  await expect(page.getByRole('table')).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.getByRole('row', { name: /Stock media/ }).getByRole('button', { name: 'Configure' }).click()
  await expect(page.getByRole('complementary', { name: 'Integration details' })).toBeVisible()
  await page.getByRole('button', { name: 'Close integration details' }).click()
  await signIn(page, '/settings', 'Settings')
  await expect(page.getByRole('navigation', { name: 'Settings sections' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})
