import { expect, test, type Page } from '@playwright/test'

const auth = `Basic ${btoa('founder:browser-secret')}`

async function signIn(page: Page, path: string, heading: string) {
  await page.goto(path)
  await page.getByLabel('Username').fill('founder')
  await page.getByLabel('Password').fill('browser-secret')
  await page.getByRole('button', { name: 'Sign in' }).click()
  await expect(page.getByRole('heading', { name: heading, exact: true })).toBeVisible()
}

test('Home, Outreach, Campaigns, and Content render persisted records in the shared shell', async ({ page, request }) => {
  await signIn(page, '/home', 'Home')
  await expect(page.getByText('Rift Dynamics')).toBeVisible()
  await page.screenshot({ path: '/tmp/autoevolve-home-workflow.png', fullPage: true })
  await expect(page).toHaveScreenshot('home-workflow.png', { fullPage: true })
  await page.getByLabel('Main navigation').getByRole('link', { name: 'Outreach' }).click()
  await expect(page.getByRole('row', { name: /Rift Dynamics/ })).toBeVisible()
  await page.getByRole('row', { name: /Rift Dynamics/ }).click()
  await expect(page.getByRole('complementary', { name: 'Outreach details' })).toContainText('Helping Rift Dynamics')
  await page.screenshot({ path: '/tmp/autoevolve-outreach-workflow.png', fullPage: true })
  await expect(page).toHaveScreenshot('outreach-workflow.png', { fullPage: true })
  await page.getByLabel('Main navigation').getByRole('link', { name: 'Campaigns' }).click()
  await expect(page.getByRole('row', { name: /Operations Efficiency Q4/ })).toBeVisible()
  await page.getByRole('row', { name: /Operations Efficiency Q4/ }).click()
  await expect(page.getByRole('complementary', { name: 'Campaign details' })).toContainText('queued')
  await page.screenshot({ path: '/tmp/autoevolve-campaigns-workflow.png', fullPage: true })
  await expect(page).toHaveScreenshot('campaigns-workflow.png', { fullPage: true })
  await page.getByLabel('Main navigation').getByRole('link', { name: 'Content' }).click()
  await expect(page.getByRole('row', { name: /Modern Ops with AI/ })).toBeVisible()
  await page.getByRole('row', { name: /Modern Ops with AI/ }).click()
  await expect(page.getByRole('complementary', { name: 'Content details' })).toContainText('Streamline operations')
  await page.screenshot({ path: '/tmp/autoevolve-content-workflow.png', fullPage: true })
  await expect(page).toHaveScreenshot('content-workflow.png', { fullPage: true })
  for (const path of ['/company/ui/home', '/company/ui/outreach', '/company/ui/campaigns', '/company/ui/content']) {
    const response = await request.get(path, { headers: { Authorization: auth } })
    expect(response.status(), path).toBe(200)
  }
})

test('Outreach approval stops at authorization and then refreshes the backend record', async ({ page, request }) => {
  await signIn(page, '/outreach', 'Outreach')
  await page.getByRole('row', { name: /Rift Dynamics/ }).click()
  const drawer = page.getByRole('complementary', { name: 'Outreach details' })
  await drawer.getByLabel('Founder action token').fill('wrong')
  await drawer.getByRole('button', { name: 'Approve draft' }).click()
  await expect(drawer.getByRole('alert')).toContainText('not authorized')
  await drawer.getByLabel('Founder action token').fill('browser-action')
  await drawer.getByRole('button', { name: 'Approve draft' }).click()
  await expect(drawer.getByRole('status')).toContainText('Draft approved')
  await expect(drawer.getByRole('button', { name: 'Send approved email' })).toBeVisible()
  const id = new URL(page.url()).searchParams.get('draft')
  const response = await request.get(`/company/ui/outreach/${id}`, { headers: { Authorization: auth } })
  expect(response.status()).toBe(200)
  expect((await response.json()).status).toBe('approved')
})

test('workflow read failures stay visible and 401 ends the session', async ({ page }) => {
  await signIn(page, '/campaigns', 'Campaigns')
  await page.route('**/company/ui/campaigns?*', route => route.fulfill({ status: 500, body: JSON.stringify({ detail: 'fixture failure' }), contentType: 'application/json' }))
  await page.getByPlaceholder('Search campaigns or objectives…').fill('failure')
  await expect(page.getByRole('heading', { name: 'Campaigns could not be loaded' })).toBeVisible()
  await expect(page.getByText('No campaigns found')).not.toBeVisible()
  await page.unroute('**/company/ui/campaigns?*')
  await page.route('**/company/ui/campaigns?*', route => route.fulfill({ status: 401, body: JSON.stringify({ detail: 'Unauthorized' }), contentType: 'application/json' }))
  await page.getByPlaceholder('Search campaigns or objectives…').fill('session')
  await expect(page.getByLabel('Username')).toBeVisible()
})

test('Buffer configuration and insights failures stop the action without hiding saved content', async ({ page }) => {
  await page.route('**/company/marketing/buffer-accounts', route => route.fulfill({
    status: 200, contentType: 'application/json',
    body: JSON.stringify({ accounts: [{ name: 'default', organization_id: null, instagram_channel_id: false, x_channel_id: false }], error: 'G3 reported no Buffer accounts' }),
  }))
  await signIn(page, '/content', 'Content')
  await page.getByRole('row', { name: /Modern Ops with AI/ }).click()
  let drawer = page.getByRole('complementary', { name: 'Content details' })
  await expect(drawer.getByRole('alert')).toContainText('G3 reported no Buffer accounts')
  await expect(drawer.getByRole('button', { name: 'Schedule post' })).toBeDisabled()
  await drawer.getByRole('button', { name: 'Close content details' }).click()
  await page.route('**/company/marketing/manual-posts/*/buffer-insights?*', route => route.fulfill({
    status: 502, contentType: 'application/json', body: JSON.stringify({ detail: 'Buffer provider unavailable' }),
  }))
  await page.getByRole('row', { name: /Published Provider Example/ }).click()
  drawer = page.getByRole('complementary', { name: 'Content details' })
  await expect(drawer.getByRole('alert')).toContainText('Buffer provider unavailable')
  await expect(drawer.getByText('A saved manual post with a confirmed Buffer ID.')).toBeVisible()
})

test('campaign and asset creation persist queued records; Buffer scheduling respects authorization and refreshes state', async ({ page, request }) => {
  await signIn(page, '/campaigns', 'Campaigns')
  await page.getByRole('button', { name: 'New campaign' }).click()
  const modal = page.getByRole('dialog', { name: 'New campaign' })
  await modal.getByLabel('Brief').fill('Help operations teams automate repetitive work')
  await modal.getByRole('button', { name: 'Create campaign' }).click()
  await expect(page.getByRole('status')).toContainText('Campaign accepted by the backend')
  await expect(page.getByRole('complementary', { name: 'Campaign details' })).toContainText('queued')
  const campaignId = new URL(page.url()).searchParams.get('campaign')
  const campaign = await request.get(`/company/ui/campaigns/${campaignId}`, { headers: { Authorization: auth } })
  expect(campaign.status()).toBe(200)
  expect((await campaign.json()).status).toBe('queued')

  await page.getByLabel('Main navigation').getByRole('link', { name: 'Content' }).click()
  await page.getByRole('button', { name: 'New asset pack' }).click()
  const assetModal = page.getByRole('dialog', { name: 'New asset pack' })
  await assetModal.getByLabel('Script').fill('A complete source script describing practical automation for operations teams.')
  await assetModal.getByRole('button', { name: 'Queue asset pack' }).click()
  await expect(page.getByRole('status')).toContainText('Asset pack queued by the backend')
  const content = await request.get('/company/ui/content', { headers: { Authorization: auth } })
  expect(content.status()).toBe(200)
  expect((await content.json()).items.some((item: { kind: string; stage: string }) => item.kind === 'asset_pack' && item.stage === 'queued')).toBe(true)

  await page.getByRole('row', { name: /Modern Ops with AI/ }).click()
  const drawer = page.getByRole('complementary', { name: 'Content details' })
  await drawer.getByLabel('Founder action token').fill('wrong')
  await drawer.getByRole('button', { name: 'Schedule post' }).click()
  await expect(drawer.getByRole('alert')).toContainText('not authorized')
  await drawer.getByLabel('Founder action token').fill('browser-action')
  await drawer.getByRole('button', { name: 'Schedule post' }).click()
  await expect(drawer.getByRole('status')).toContainText('Buffer scheduling confirmed by the backend')
  await expect(drawer).toContainText('scheduled')
  const refreshed = await request.get('/company/ui/content', { headers: { Authorization: auth } })
  expect(refreshed.status()).toBe(200)
  expect((await refreshed.json()).items.find((item: { title: string }) => item.title === 'Modern Ops with AI').buffer_status).toBe('scheduled')
})

test('Content shows only provider-confirmed Buffer insights for a saved post ID', async ({ page, request }) => {
  await signIn(page, '/content', 'Content')
  await page.getByRole('row', { name: /Published Provider Example/ }).click()
  const drawer = page.getByRole('complementary', { name: 'Content details' })
  await expect(drawer.getByRole('heading', { name: 'Buffer post insights' })).toBeVisible()
  await expect(drawer.getByText('Reactions')).toBeVisible()
  await expect(drawer.getByText('12', { exact: true })).toBeVisible()
  await expect(drawer.getByText('sent', { exact: true })).toBeVisible()
  const content = await request.get('/company/ui/content', { headers: { Authorization: auth } })
  const id = (await content.json()).items.find((item: { title: string }) => item.title === 'Published Provider Example').id
  const response = await request.get(`/company/marketing/manual-posts/${id}/buffer-insights?post_id=buffer-sent-1`, { headers: { Authorization: auth } })
  expect(response.status()).toBe(200)
  expect((await response.json()).status).toBe('sent')
})

test('manual post upload creates a ready saved record without claiming scheduling', async ({ page, request }) => {
  await signIn(page, '/content', 'Content')
  await page.getByRole('button', { name: 'New manual post' }).click()
  const dialog = page.getByRole('dialog', { name: 'New manual post' })
  await dialog.getByLabel('Platform').selectOption('x')
  await dialog.getByLabel('Destination URL').fill('https://example.test/offer')
  await dialog.getByLabel('CTA label').fill('Read the guide')
  await dialog.getByLabel('Media').setInputFiles('tests/e2e/contacts.spec.ts-snapshots/contacts-desktop-linux.png')
  await dialog.getByRole('button', { name: 'Save manual post' }).click()
  await expect(page.getByRole('status')).toContainText('Manual post saved and ready')
  const response = await request.get('/company/ui/content', { headers: { Authorization: auth } })
  expect(response.status()).toBe(200)
  const saved = (await response.json()).items.find((item: { kind: string; stage: string; asset_count: number; platform: string }) => item.kind === 'manual_post' && item.stage === 'ready' && item.asset_count === 1 && item.platform === 'x')
  expect(saved).toBeTruthy()
  expect(saved.stage).toBe('ready')
  expect(saved.buffer_status).toBe('not_started')
})

test('Home incident card opens the saved incident projection', async ({ page, request }) => {
  await signIn(page, '/home', 'Home')
  await page.getByRole('link', { name: /open service incidents/ }).click()
  await expect(page).toHaveURL(/\/integrations\?view=incidents/)
  await expect(page.getByRole('heading', { name: 'Service incidents' })).toBeVisible()
  await expect(page.getByText('hunter · provider_unavailable')).toBeVisible()
  const response = await request.get('/company/incidents?limit=100', { headers: { Authorization: auth } })
  expect(response.status()).toBe(200)
  expect((await response.json()).incidents[0].status).toBe('open')
})

test('bookmarked legacy workflow URLs open the modern sign-in and shell', async ({ page }) => {
  await page.goto('/operations/sales/email')
  await expect(page).toHaveURL(/\/outreach$/)
  await page.getByLabel('Username').fill('founder')
  await page.getByLabel('Password').fill('browser-secret')
  await page.getByRole('button', { name: 'Sign in' }).click()
  await expect(page.getByRole('heading', { name: 'Outreach', exact: true })).toBeVisible()
})
